### ISSUE TITLE
Sorting on translated field, ascending only.

### ISSUE THREAD

**Issue by tanthammar** [spatie/nova-translatable#16] opened 2018-11-06 10:37 UTC
Nova 1.1.7

In index view.
Sorting on a translated field (column) only works in ascending order.
Second click, to toggle ascending/descending sorting, does nothing.

**Comment by freekmurze** [comment] 2018-11-06 11:20
Feel free to send a PR that fixes this

**Comment by mrmonat** [comment] 2019-01-04 16:55
I think this has nothing to do with this package, the problem is how Nova handles the underlying json columns when sorting / searching. 

MySQL isn't able to sort based on  json column values with a simple ```ORDER BY column_name ASC/DESC```.

The query should look something like this to work properly: 
```ORDER BY `column` -> '$."en"' DESC```

**Comment by freekmurze** [comment] 2019-01-08 10:01
Closing this as it can't be handled in the package.

**Closed by freekmurze** 2019-01-08 10:01 UTC
Labels: bug, good first issue, help wanted

**Comment by mrmonat** [comment] 2019-01-28 22:54
Here is a trait, that is a possible solution for the problem:

```
<?php

namespace App\Nova\Traits;

trait SortTranslatableFields
{
    protected static function applyOrderings($query, array $orderings)
    {
        $locale = app()->getLocale();
        $translatableAttributes = app(self::$model)->make()->getTranslatableAttributes();

        foreach ($orderings as $column => $direction) {
            if (in_array($column, $translatableAttributes)) {
                unset($orderings[$column]);
                $query->orderByRaw("`{$column}` -> '$.{$locale}' {$direction}");
            }
        }

        return parent::applyOrderings($query, $orderings);
    }
}
```

Maybe this Trait could be added to the package, but you have to manually "use" it in every Nova resource, where you use Translatable fields.

**Comment by tanthammar** [comment] 2019-11-01 18:24
I made a macro. That way I can set it once and forget about it.

```php
use Spatie\Translatable\HasTranslations;
use Illuminate\Database\Eloquent\Builder;


Builder::macro('orderByTranslation', function ($field, $order = 'asc', $locale = null) {
            if (
                in_array(HasTranslations::class, class_uses($this->model))
                && in_array($field, $this->model->translatable)
            ) {
                $locale = $locale ?? app()->getLocale();
                $field .= '->' . $locale;
                $this->query->orderBy($field, $order);
            } else {
                $this->query->orderBy($field, $order);
            }
            return $this;
        });
```

**Comment by NessterGit** [comment] 2022-06-03 16:22
> Here is a trait, that is a possible solution for the problem:
> 
> ```
> <?php
> 
> namespace App\Nova\Traits;
> 
> trait SortTranslatableFields
> {
>     protected static function applyOrderings($query, array $orderings)
>     {
>         $locale = app()->getLocale();
>         $translatableAttributes = app(self::$model)->make()->getTranslatableAttributes();
> 
>         foreach ($orderings as $column => $direction) {
>             if (in_array($column, $translatableAttributes)) {
>                 unset($orderings[$column]);
>                 $query->orderByRaw("`{$column}` -> '$.{$locale}' {$direction}");
>             }
>         }
> 
>         return parent::applyOrderings($query, $orderings);
>     }
> }
> ```
> 
> Maybe this Trait could be added to the package, but you have to manually "use" it in every Nova resource, where you use Translatable fields.

For those who land here, trying to go the **Trait** way, on **PostgreSQL**, here is the syntax to access your JSON fields:
`$query->orderByRaw("{$column}->>'{$locale}' {$direction}");`
You may have to play with -> and ->> after the column name, or cast to string after accessing with ->
